databases:
  - name: NoteShareSystem
    databaseName: NoteShareSystem
    user: NoteShareSystem



services:
  - type: web
    name: NoteShareSystem
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn NoteShareSystem.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: NoteShareSystem
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      autoDeploy: true