# Generated by Django 4.0.3 on 2022-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pauthor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pdata',
            field=models.TextField(blank=True, default=''),
        ),
    ]
