# Generated by Django 4.0.3 on 2022-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_productmodel_pauthor_productmodel_pdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
