# Generated by Django 4.0.3 on 2022-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_productmodel_pauthor_introduce_productmodel_pdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdata',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(default=''),
        ),
    ]
