# Generated by Django 4.0.3 on 2022-05-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_alter_productmodel_pdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Simple_pdescription',
            field=models.TextField(default='', max_length=290),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(default=''),
        ),
    ]
