# Generated by Django 4.0.3 on 2022-05-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_alter_productmodel_pimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='pimages',
        ),
    ]
