# Generated by Django 4.0.3 on 2022-05-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0009_remove_productmodel_pimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pimages',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
