# Generated by Django 4.0.3 on 2022-05-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0013_remove_productmodel_upload_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
