# Generated by Django 4.0.4 on 2022-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0020_alter_productmodel_pimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pcreatepeople',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdata',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pimages',
            field=models.ImageField(blank=True, default=0, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
