# Generated by Django 4.0.4 on 2022-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0021_productmodel_pcreatepeople_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='catego',
            field=models.CharField(choices=[('最新', '最新'), ('精選', '精選'), ('普通', '普通'), ('其他', '其他')], default='最新', max_length=10),
        ),
    ]
