# Generated by Django 4.0.4 on 2022-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0022_productmodel_catego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdata',
            field=models.TextField(default='', max_length=80),
        ),
    ]
