# Generated by Django 4.0.4 on 2022-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0024_alter_productmodel_pauthor_introduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Simple_pdescription',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(default='', max_length=300),
        ),
    ]
