# Generated by Django 4.0.5 on 2022-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0026_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pimages',
            field=models.ImageField(default=0, upload_to='image/'),
        ),
    ]
