# Generated by Django 4.0.5 on 2022-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0028_alter_productmodel_pimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='special_offer',
            field=models.IntegerField(default=0),
        ),
    ]
