# Generated by Django 4.0.5 on 2022-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0029_productmodel_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='press',
            field=models.IntegerField(default=0),
        ),
    ]
