# Generated by Django 4.1.1 on 2022-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0032_alter_productmodel_pprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pcreatepeople',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pprice',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='special_offer',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
