# Generated by Django 4.0.5 on 2022-10-04 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0034_alter_productmodel_pcreatepeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
