# Generated by Django 4.0.5 on 2022-10-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0035_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
