# Generated by Django 4.1.1 on 2022-10-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0038_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor',
            field=models.CharField(default='', max_length=10),
        ),
    ]
