# Generated by Django 4.1.1 on 2022-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0039_alter_productmodel_pauthor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='file_title',
            field=models.CharField(blank=True, default='預設檔名', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='uploadedFile',
            field=models.FileField(blank=True, default='預設', null=True, upload_to='file/'),
        ),
    ]
