# Generated by Django 4.1.1 on 2022-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0042_productmodel_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='file_title',
            field=models.CharField(blank=True, default='預設檔名', max_length=30, null=True),
        ),
    ]
