# Generated by Django 4.1.1 on 2022-10-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0043_alter_productmodel_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(default='', max_length=600),
        ),
    ]
