# Generated by Django 4.0.5 on 2022-10-27 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexapp', '0045_alter_productmodel_pimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
