# Generated by Django 4.1.1 on 2022-11-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0046_productmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='author',
        ),
    ]
