# Generated by Django 4.1.1 on 2022-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0047_remove_productmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdate',
            field=models.DateField(auto_now_add=True, max_length=10),
        ),
    ]
