# Generated by Django 4.1.1 on 2022-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0048_alter_productmodel_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdate',
            field=models.CharField(default='date.today', max_length=10),
        ),
    ]
