# Generated by Django 4.1.1 on 2022-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0052_alter_productmodel_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pdate',
            field=models.DateTimeField(auto_now=True, verbose_name='最後修改日期'),
        ),
    ]
