# Generated by Django 4.1.1 on 2022-11-21 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0053_alter_productmodel_pdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pdate',
            new_name='mod_date',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Simple_pdescription',
            field=models.TextField(max_length=150, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='catego',
            field=models.CharField(choices=[('最新', '最新'), ('精選', '精選'), ('普通', '普通'), ('其他', '其他')], default='最新', max_length=5, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True, verbose_name='檔案日期'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='file_title',
            field=models.CharField(default='預設檔名', max_length=30, verbose_name='檔名'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor',
            field=models.CharField(max_length=10, verbose_name='筆者'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pauthor_introduce',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='筆者簡介'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pcreatepeople',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='新增者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdata',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='歸類'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pdescription',
            field=models.TextField(max_length=600, verbose_name='詳細介紹'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pimages',
            field=models.ImageField(blank=True, default=0, upload_to='image', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pname',
            field=models.CharField(max_length=20, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='特價'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='press',
            field=models.IntegerField(default=0, verbose_name='點擊次數'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='special_offer',
            field=models.IntegerField(null=True, verbose_name='原價'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='uploadedFile',
            field=models.FileField(default='預設', upload_to='file', verbose_name='檔案'),
        ),
    ]
