# Generated by Django 4.1.1 on 2022-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0055_alter_productmodel_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pcreatepeople',
            field=models.CharField(blank=True, max_length=20, verbose_name='新增者'),
        ),
    ]
