# Generated by Django 4.1.1 on 2022-11-21 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0056_alter_productmodel_pcreatepeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最後修改日期'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
