# Generated by Django 4.1.1 on 2022-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0057_alter_productmodel_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='啟用狀態'),
        ),
    ]
