# Generated by Django 4.1.1 on 2022-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0059_alter_productmodel_file_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pimages',
            field=models.ImageField(upload_to='image', verbose_name='圖片'),
        ),
    ]
