# Generated by Django 4.1.1 on 2022-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0060_alter_productmodel_pimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最後翻閱日期'),
        ),
    ]
