# Generated by Django 4.1.1 on 2022-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0062_alter_productmodel_file_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='file_title',
            field=models.CharField(max_length=30, verbose_name='檔名'),
        ),
    ]
