# Generated by Django 4.0.5 on 2022-12-06 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0063_alter_productmodel_file_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20, verbose_name='名稱')),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('enabled', models.BooleanField(default=False, verbose_name='啟用狀態')),
                ('pcreatepeople', models.CharField(blank=True, max_length=20, verbose_name='新增者')),
                ('field_name', models.EmailField(max_length=254)),
            ],
        ),
    ]
