# Generated by Django 4.0.5 on 2022-12-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0064_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorized',
            name='pprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='售價'),
        ),
        migrations.AddField(
            model_name='authorized',
            name='price_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='收益'),
        ),
    ]
