# Generated by Django 4.0.5 on 2022-12-06 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0065_authorized_pprice_authorized_price_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorized',
            name='enabled',
        ),
        migrations.AddField(
            model_name='authorized',
            name='status',
            field=models.BooleanField(default=False, verbose_name='寄送狀態'),
        ),
        migrations.AlterField(
            model_name='authorized',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='購買日期'),
        ),
    ]
