# Generated by Django 4.0.5 on 2022-12-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0066_remove_authorized_enabled_authorized_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorized',
            old_name='field_name',
            new_name='field_mail',
        ),
    ]
