# Generated by Django 4.1.1 on 2022-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0067_rename_field_name_authorized_field_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorized',
            name='Checkbox',
            field=models.BooleanField(default=False, verbose_name='確認與否'),
        ),
    ]
