# Generated by Django 4.1.1 on 2022-12-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0070_authorized_file_authorized_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorized',
            name='mod_date',
            field=models.CharField(default=0, max_length=20, verbose_name='購買日期'),
        ),
    ]
