# Generated by Django 4.1.1 on 2022-12-08 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0071_alter_authorized_mod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorized',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
