# Generated by Django 4.1.1 on 2022-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0074_productmodel_pcreatepeople_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pcreatepeople_email',
            field=models.CharField(default=0, max_length=30, verbose_name='新增者郵箱'),
        ),
    ]
