# Generated by Django 4.0.3 on 2022-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='catego',
            field=models.CharField(choices=[('更新', '更新'), ('活動', '活動'), ('其他', '其他'), ('公告', '公告')], max_length=10),
        ),
    ]
