# Generated by Django 4.1.1 on 2022-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmapp', '0002_alter_newsunit_catego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='catego',
            field=models.CharField(choices=[('更新', '更新'), ('活動', '活動'), ('其他', '其他'), ('公告', '公告')], max_length=10, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='啟用狀態'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='message',
            field=models.TextField(verbose_name='訊息'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='新增者'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='press',
            field=models.IntegerField(default=0, verbose_name='點擊次數'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='pubtime',
            field=models.DateTimeField(auto_now=True, verbose_name='公告時間'),
        ),
        migrations.AlterField(
            model_name='newsunit',
            name='title',
            field=models.CharField(max_length=50, verbose_name='標題'),
        ),
    ]
